### PR TITLE
Drop redundant enum members prefixes

### PR DESCRIPTION
**Pull request by Sija**
Refs https://github.com/naqvis/crystal-vips/pull/6#issuecomment-1951025507

### CODE REVIEW

**Comment by naqvis** [comment]
Many thanks again @Sija ❤️

**Comment by Sija** [comment]
You're welcome! Thank you for this shard, it enabled me to implement dynamic resize functionality in [gphoto2-web](https://github.com/Sija/gphoto2-web) app ❤️

**Comment by Sija** [comment]
Would you mind doing a new release?

**Comment by naqvis** [comment]
> Would you mind doing a new release?

Done. Pushed v0.1.5 release

**Comment by Sija** [comment]
@naqvis Many thanks 🙏

**Pull request merged**
