### PR TITLE
Update enums with missing members and `@[Flags]` annotation

### LINKED ISSUE #5: Loading image fails with `Unknown enum LibVips::VipsArgumentFlags value: 274 (Exception)`
This happens for at least `Image.magickload_buffer` method, and IIRC some others as well.
This happens due to this line:

https://github.com/naqvis/crystal-vips/blob/1c40bc01dc31e8d40a4fc745f7ae0b47898299fa/src/vips/introspect.cr#L90

It's due to the missing enum member:

```c
VIPS_ARGUMENT_NON_HASHABLE = 256
```

https://github.com/libvips/libvips/blob/7258df0c4b5e9056ea24055121a2e620dfb1b3a1/libvips/include/vips/object.h#L76

### PR DESCRIPTION
**Pull request by Sija**
Resolves #5
Refs https://github.com/libvips/libvips/pull/3370

### CODE REVIEW

**Comment by Sija** [comment]
While we're at it, shouldn't `VipsOperationFlags` and `VipsForeignFlags` enums have `@[Flags]` annotation too?

**Comment by naqvis** [comment]
> While we're at it, shouldn't `VipsOperationFlags` and `VipsForeignFlags` enums have `@[Flags]` annotation too?

Thanks @Sija 👍 . Yeah agree these two enums should be flaged with `@[Flags]` annotation. Appreciate if you can please apply these changes along with this PR.

**Comment by Sija** [comment]
@naqvis Done.

**Comment by Sija** [comment]
I'm also wondering, are long enum member names intentional?
`VipsArgumentFlags::Required` vs `VipsOperationFlags::VipsOperationSequential`

**Comment by Sija** [comment]
I'd suggest to drop the prefixes from the enum member names, like in `VipsArgumentFlags`.

**Comment by naqvis** [comment]
> I'd suggest to drop the prefixes from the enum member names, like in `VipsArgumentFlags`.

Yeah agree. Reason they are there is because this `lib.cr` was generated via `crystal_lib` and I didn't spend time on fixing generated code. Definitely would be great if such repetition can be avoided.

**Comment by naqvis** [comment]
I'm going to go with merging this PR, while can leave the refactoring/clean-up task to separate PR.

**Pull request merged**
